name: should-republish-evans
inputs:
  flp_api_endpoint:
    required: true
  flp_api_token:
    required: true
outputs:
  should_republish:
    description: "'true' if evans needs to be republished"
  build_meta:
    description: json to upload as latest build data if republish succeeds
runs:
  using: node16
  main: ./bundled/index.js
